services:
  frontend:
    build: frontend
    ports:
      - 8080:80
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    build: backend
    depends_on:
      - database
    restart: unless-stopped
    environment:
      - BACKEND_PORT
      - SECRET_CODE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  database:
    image: "postgres:16.1-alpine3.18"
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
